"""Public service API for Plex Dupefinder v2."""

from .domain import (
    AudioTrack,
    DuplicateGroup,
    LibrarySection,
    MediaCandidate,
    MediaPart,
    MediaVersion,
    MetadataItem,
    PlexConnection,
    PlexIdentity,
    ScoreResult,
)
from .plex_gateway import (
    DeleteReceipt,
    PlexDeleteUncertainError,
    PlexGateway,
    PlexGatewayError,
    PlexHttpError,
    PlexIdentityMismatch,
    PlexProtocolError,
    PlexTransportError,
)
from .plex_mate_provider import (
    PlexMateConfigurationError,
    PlexMateConnectionProvider,
    PlexMateProvider,
    PlexMateProviderError,
    PlexMateUnavailable,
)
from .score_engine import (
    DEFAULT_FILENAME_SCORES,
    RankedCandidate,
    ScoreConfig,
    ScoreDecision,
    ScoreEngine,
    stable_media_id_key,
)
from .subtitle_finder import (
    DEFAULT_SUBTITLE_DIRS,
    DEFAULT_SUBTITLE_EXTENSIONS,
    SubtitleDeleteResult,
    SubtitleFinder,
    delete_sidecars,
    find_sidecars,
    normalize_extensions,
)

__all__ = [
    "AudioTrack",
    "DEFAULT_SUBTITLE_DIRS",
    "DEFAULT_SUBTITLE_EXTENSIONS",
    "DEFAULT_FILENAME_SCORES",
    "DeleteReceipt",
    "DuplicateGroup",
    "LibrarySection",
    "MediaCandidate",
    "MediaPart",
    "MediaVersion",
    "MetadataItem",
    "PlexConnection",
    "PlexDeleteUncertainError",
    "PlexGateway",
    "PlexGatewayError",
    "PlexHttpError",
    "PlexIdentity",
    "PlexIdentityMismatch",
    "PlexMateConfigurationError",
    "PlexMateConnectionProvider",
    "PlexMateProvider",
    "PlexMateProviderError",
    "PlexMateUnavailable",
    "PlexProtocolError",
    "PlexTransportError",
    "RankedCandidate",
    "ScoreConfig",
    "ScoreDecision",
    "ScoreEngine",
    "ScoreResult",
    "SubtitleDeleteResult",
    "SubtitleFinder",
    "delete_sidecars",
    "find_sidecars",
    "normalize_extensions",
    "stable_media_id_key",
]
